# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Deploy CPM files to the Vault
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Uploads CPM files to the Vault
        shell: powershell
        run: |
          $VaultPassword =  ${{ secrets.VAULT_PASSWORD }}
          $VaultCredentialPassword = ConvertTo-SecureString -String $VaultPassword -AsPlainText -Force
          $VaultCredential = New-Object System.Management.Automation.PSCredential (Administrator, $VaultCredentialPassword)
          . .\Update-PASPlatformFiles
          Update-PASPlatformFiles `
            -PacliClientPath C:\PACLI\Pacli.exe `
            -VaultAddress 192.168.0.50 `
            -VaultCredential $VaultCredential `
            -PlatformId RealVNCServiceMode `
            -CPMPolicyFile .\cpm\Policy-RealVNCServiceMode.ini `
            -PVWASettingsFile .\cpm\Policy-RealVNC.xml `
            -Path .\cpm\
