name: Deploy platform and plugin files to the CyberArk Vault on release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy CPM files to the Vault
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Uploads CPM files to the Vault
        shell: powershell
        run: |
          $env:HOMEDRIVE = ""
          $env:HomePath = "${{ runner.temp }}"
          Import-Module PoShPACLI
          $VaultCredential = New-Object System.Management.Automation.PSCredential ("Administrator", (ConvertTo-SecureString -String ${{ secrets.VAULT_PASSWORD }} -AsPlainText -Force))
          . .\Update-PASPlatformFiles
          Update-PASPlatformFiles `
            -PacliClientPath C:\PACLI\Pacli.exe `
            -VaultAddress 192.168.0.50 `
            -VaultCredential $VaultCredential `
            -PlatformId RealVNCServiceMode `
            -CPMPolicyFile .\cpm\Policy-RealVNCServiceMode.ini `
            -PVWASettingsFile .\cpm\Policy-RealVNC.xml `
            -Path .\cpm\
